#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp_Parcial_DesarrolloWeb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_instituto")]
	public partial class Data_db_InstitutoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTurno(Turno instance);
    partial void UpdateTurno(Turno instance);
    partial void DeleteTurno(Turno instance);
    partial void InsertAlumno(Alumno instance);
    partial void UpdateAlumno(Alumno instance);
    partial void DeleteAlumno(Alumno instance);
    partial void InsertComentario(Comentario instance);
    partial void UpdateComentario(Comentario instance);
    partial void DeleteComentario(Comentario instance);
    #endregion
		
		public Data_db_InstitutoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db_institutoConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Data_db_InstitutoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_db_InstitutoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_db_InstitutoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_db_InstitutoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Turno> Turnos
		{
			get
			{
				return this.GetTable<Turno>();
			}
		}
		
		public System.Data.Linq.Table<Alumno> Alumnos
		{
			get
			{
				return this.GetTable<Alumno>();
			}
		}
		
		public System.Data.Linq.Table<Comentario> Comentarios
		{
			get
			{
				return this.GetTable<Comentario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Turnos")]
	public partial class Turno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_turno;
		
		private string _turno1;
		
		private EntitySet<Alumno> _Alumnos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_turnoChanging(int value);
    partial void Onid_turnoChanged();
    partial void Onturno1Changing(string value);
    partial void Onturno1Changed();
    #endregion
		
		public Turno()
		{
			this._Alumnos = new EntitySet<Alumno>(new Action<Alumno>(this.attach_Alumnos), new Action<Alumno>(this.detach_Alumnos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_turno", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_turno
		{
			get
			{
				return this._id_turno;
			}
			set
			{
				if ((this._id_turno != value))
				{
					this.Onid_turnoChanging(value);
					this.SendPropertyChanging();
					this._id_turno = value;
					this.SendPropertyChanged("id_turno");
					this.Onid_turnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="turno", Storage="_turno1", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string turno1
		{
			get
			{
				return this._turno1;
			}
			set
			{
				if ((this._turno1 != value))
				{
					this.Onturno1Changing(value);
					this.SendPropertyChanging();
					this._turno1 = value;
					this.SendPropertyChanged("turno1");
					this.Onturno1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Turno_Alumno", Storage="_Alumnos", ThisKey="id_turno", OtherKey="fk_turno")]
		public EntitySet<Alumno> Alumnos
		{
			get
			{
				return this._Alumnos;
			}
			set
			{
				this._Alumnos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Alumnos(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Turno = this;
		}
		
		private void detach_Alumnos(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Turno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alumnos")]
	public partial class Alumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_alumno;
		
		private string _dni;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _email;
		
		private int _fk_turno;
		
		private EntitySet<Comentario> _Comentarios;
		
		private EntityRef<Turno> _Turno;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_alumnoChanging(int value);
    partial void Onid_alumnoChanged();
    partial void OndniChanging(string value);
    partial void OndniChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onfk_turnoChanging(int value);
    partial void Onfk_turnoChanged();
    #endregion
		
		public Alumno()
		{
			this._Comentarios = new EntitySet<Comentario>(new Action<Comentario>(this.attach_Comentarios), new Action<Comentario>(this.detach_Comentarios));
			this._Turno = default(EntityRef<Turno>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_alumno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_alumno
		{
			get
			{
				return this._id_alumno;
			}
			set
			{
				if ((this._id_alumno != value))
				{
					this.Onid_alumnoChanging(value);
					this.SendPropertyChanging();
					this._id_alumno = value;
					this.SendPropertyChanged("id_alumno");
					this.Onid_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string dni
		{
			get
			{
				return this._dni;
			}
			set
			{
				if ((this._dni != value))
				{
					this.OndniChanging(value);
					this.SendPropertyChanging();
					this._dni = value;
					this.SendPropertyChanged("dni");
					this.OndniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_turno", DbType="Int NOT NULL")]
		public int fk_turno
		{
			get
			{
				return this._fk_turno;
			}
			set
			{
				if ((this._fk_turno != value))
				{
					if (this._Turno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_turnoChanging(value);
					this.SendPropertyChanging();
					this._fk_turno = value;
					this.SendPropertyChanged("fk_turno");
					this.Onfk_turnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumno_Comentario", Storage="_Comentarios", ThisKey="id_alumno", OtherKey="fk_alumno")]
		public EntitySet<Comentario> Comentarios
		{
			get
			{
				return this._Comentarios;
			}
			set
			{
				this._Comentarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Turno_Alumno", Storage="_Turno", ThisKey="fk_turno", OtherKey="id_turno", IsForeignKey=true)]
		public Turno Turno
		{
			get
			{
				return this._Turno.Entity;
			}
			set
			{
				Turno previousValue = this._Turno.Entity;
				if (((previousValue != value) 
							|| (this._Turno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Turno.Entity = null;
						previousValue.Alumnos.Remove(this);
					}
					this._Turno.Entity = value;
					if ((value != null))
					{
						value.Alumnos.Add(this);
						this._fk_turno = value.id_turno;
					}
					else
					{
						this._fk_turno = default(int);
					}
					this.SendPropertyChanged("Turno");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comentarios(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Alumno = this;
		}
		
		private void detach_Comentarios(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Alumno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comentarios")]
	public partial class Comentario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_comentario;
		
		private string _comentario1;
		
		private int _fk_alumno;
		
		private EntityRef<Alumno> _Alumno;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_comentarioChanging(int value);
    partial void Onid_comentarioChanged();
    partial void Oncomentario1Changing(string value);
    partial void Oncomentario1Changed();
    partial void Onfk_alumnoChanging(int value);
    partial void Onfk_alumnoChanged();
    #endregion
		
		public Comentario()
		{
			this._Alumno = default(EntityRef<Alumno>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_comentario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_comentario
		{
			get
			{
				return this._id_comentario;
			}
			set
			{
				if ((this._id_comentario != value))
				{
					this.Onid_comentarioChanging(value);
					this.SendPropertyChanging();
					this._id_comentario = value;
					this.SendPropertyChanged("id_comentario");
					this.Onid_comentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="comentario", Storage="_comentario1", DbType="VarChar(700) NOT NULL", CanBeNull=false)]
		public string comentario1
		{
			get
			{
				return this._comentario1;
			}
			set
			{
				if ((this._comentario1 != value))
				{
					this.Oncomentario1Changing(value);
					this.SendPropertyChanging();
					this._comentario1 = value;
					this.SendPropertyChanged("comentario1");
					this.Oncomentario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_alumno", DbType="Int NOT NULL")]
		public int fk_alumno
		{
			get
			{
				return this._fk_alumno;
			}
			set
			{
				if ((this._fk_alumno != value))
				{
					if (this._Alumno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_alumnoChanging(value);
					this.SendPropertyChanging();
					this._fk_alumno = value;
					this.SendPropertyChanged("fk_alumno");
					this.Onfk_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumno_Comentario", Storage="_Alumno", ThisKey="fk_alumno", OtherKey="id_alumno", IsForeignKey=true)]
		public Alumno Alumno
		{
			get
			{
				return this._Alumno.Entity;
			}
			set
			{
				Alumno previousValue = this._Alumno.Entity;
				if (((previousValue != value) 
							|| (this._Alumno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Alumno.Entity = null;
						previousValue.Comentarios.Remove(this);
					}
					this._Alumno.Entity = value;
					if ((value != null))
					{
						value.Comentarios.Add(this);
						this._fk_alumno = value.id_alumno;
					}
					else
					{
						this._fk_alumno = default(int);
					}
					this.SendPropertyChanged("Alumno");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
