#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp_Parcial_DesarrolloWeb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_Instituto")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertturno(turno instance);
    partial void Updateturno(turno instance);
    partial void Deleteturno(turno instance);
    partial void Insertcomentario(comentario instance);
    partial void Updatecomentario(comentario instance);
    partial void Deletecomentario(comentario instance);
    partial void Insertalumno(alumno instance);
    partial void Updatealumno(alumno instance);
    partial void Deletealumno(alumno instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db_InstitutoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<turno> turnos
		{
			get
			{
				return this.GetTable<turno>();
			}
		}
		
		public System.Data.Linq.Table<comentario> comentarios
		{
			get
			{
				return this.GetTable<comentario>();
			}
		}
		
		public System.Data.Linq.Table<alumno> alumnos
		{
			get
			{
				return this.GetTable<alumno>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.turnos")]
	public partial class turno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_turno;
		
		private string _turno1;
		
		private EntitySet<alumno> _alumnos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_turnoChanging(int value);
    partial void Onid_turnoChanged();
    partial void Onturno1Changing(string value);
    partial void Onturno1Changed();
    #endregion
		
		public turno()
		{
			this._alumnos = new EntitySet<alumno>(new Action<alumno>(this.attach_alumnos), new Action<alumno>(this.detach_alumnos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_turno", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_turno
		{
			get
			{
				return this._id_turno;
			}
			set
			{
				if ((this._id_turno != value))
				{
					this.Onid_turnoChanging(value);
					this.SendPropertyChanging();
					this._id_turno = value;
					this.SendPropertyChanged("id_turno");
					this.Onid_turnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="turno", Storage="_turno1", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string turno1
		{
			get
			{
				return this._turno1;
			}
			set
			{
				if ((this._turno1 != value))
				{
					this.Onturno1Changing(value);
					this.SendPropertyChanging();
					this._turno1 = value;
					this.SendPropertyChanged("turno1");
					this.Onturno1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="turno_alumno", Storage="_alumnos", ThisKey="id_turno", OtherKey="fk_turno")]
		public EntitySet<alumno> alumnos
		{
			get
			{
				return this._alumnos;
			}
			set
			{
				this._alumnos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_alumnos(alumno entity)
		{
			this.SendPropertyChanging();
			entity.turno = this;
		}
		
		private void detach_alumnos(alumno entity)
		{
			this.SendPropertyChanging();
			entity.turno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.comentarios")]
	public partial class comentario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_comentario;
		
		private string _comentario1;
		
		private int _fk_alumno;
		
		private EntityRef<alumno> _alumno;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_comentarioChanging(int value);
    partial void Onid_comentarioChanged();
    partial void Oncomentario1Changing(string value);
    partial void Oncomentario1Changed();
    partial void Onfk_alumnoChanging(int value);
    partial void Onfk_alumnoChanged();
    #endregion
		
		public comentario()
		{
			this._alumno = default(EntityRef<alumno>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_comentario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_comentario
		{
			get
			{
				return this._id_comentario;
			}
			set
			{
				if ((this._id_comentario != value))
				{
					this.Onid_comentarioChanging(value);
					this.SendPropertyChanging();
					this._id_comentario = value;
					this.SendPropertyChanged("id_comentario");
					this.Onid_comentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="comentario", Storage="_comentario1", DbType="VarChar(700) NOT NULL", CanBeNull=false)]
		public string comentario1
		{
			get
			{
				return this._comentario1;
			}
			set
			{
				if ((this._comentario1 != value))
				{
					this.Oncomentario1Changing(value);
					this.SendPropertyChanging();
					this._comentario1 = value;
					this.SendPropertyChanged("comentario1");
					this.Oncomentario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_alumno", DbType="Int NOT NULL")]
		public int fk_alumno
		{
			get
			{
				return this._fk_alumno;
			}
			set
			{
				if ((this._fk_alumno != value))
				{
					if (this._alumno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_alumnoChanging(value);
					this.SendPropertyChanging();
					this._fk_alumno = value;
					this.SendPropertyChanged("fk_alumno");
					this.Onfk_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="alumno_comentario", Storage="_alumno", ThisKey="fk_alumno", OtherKey="id_alumno", IsForeignKey=true)]
		public alumno alumno
		{
			get
			{
				return this._alumno.Entity;
			}
			set
			{
				alumno previousValue = this._alumno.Entity;
				if (((previousValue != value) 
							|| (this._alumno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._alumno.Entity = null;
						previousValue.comentarios.Remove(this);
					}
					this._alumno.Entity = value;
					if ((value != null))
					{
						value.comentarios.Add(this);
						this._fk_alumno = value.id_alumno;
					}
					else
					{
						this._fk_alumno = default(int);
					}
					this.SendPropertyChanged("alumno");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.alumnos")]
	public partial class alumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_alumno;
		
		private int _dni;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _email;
		
		private int _fk_turno;
		
		private EntitySet<comentario> _comentarios;
		
		private EntityRef<turno> _turno;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_alumnoChanging(int value);
    partial void Onid_alumnoChanged();
    partial void OndniChanging(int value);
    partial void OndniChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onfk_turnoChanging(int value);
    partial void Onfk_turnoChanged();
    #endregion
		
		public alumno()
		{
			this._comentarios = new EntitySet<comentario>(new Action<comentario>(this.attach_comentarios), new Action<comentario>(this.detach_comentarios));
			this._turno = default(EntityRef<turno>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_alumno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_alumno
		{
			get
			{
				return this._id_alumno;
			}
			set
			{
				if ((this._id_alumno != value))
				{
					this.Onid_alumnoChanging(value);
					this.SendPropertyChanging();
					this._id_alumno = value;
					this.SendPropertyChanged("id_alumno");
					this.Onid_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni", DbType="Int NOT NULL")]
		public int dni
		{
			get
			{
				return this._dni;
			}
			set
			{
				if ((this._dni != value))
				{
					this.OndniChanging(value);
					this.SendPropertyChanging();
					this._dni = value;
					this.SendPropertyChanged("dni");
					this.OndniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_turno", DbType="Int NOT NULL")]
		public int fk_turno
		{
			get
			{
				return this._fk_turno;
			}
			set
			{
				if ((this._fk_turno != value))
				{
					if (this._turno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_turnoChanging(value);
					this.SendPropertyChanging();
					this._fk_turno = value;
					this.SendPropertyChanged("fk_turno");
					this.Onfk_turnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="alumno_comentario", Storage="_comentarios", ThisKey="id_alumno", OtherKey="fk_alumno")]
		public EntitySet<comentario> comentarios
		{
			get
			{
				return this._comentarios;
			}
			set
			{
				this._comentarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="turno_alumno", Storage="_turno", ThisKey="fk_turno", OtherKey="id_turno", IsForeignKey=true)]
		public turno turno
		{
			get
			{
				return this._turno.Entity;
			}
			set
			{
				turno previousValue = this._turno.Entity;
				if (((previousValue != value) 
							|| (this._turno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._turno.Entity = null;
						previousValue.alumnos.Remove(this);
					}
					this._turno.Entity = value;
					if ((value != null))
					{
						value.alumnos.Add(this);
						this._fk_turno = value.id_turno;
					}
					else
					{
						this._fk_turno = default(int);
					}
					this.SendPropertyChanged("turno");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_comentarios(comentario entity)
		{
			this.SendPropertyChanging();
			entity.alumno = this;
		}
		
		private void detach_comentarios(comentario entity)
		{
			this.SendPropertyChanging();
			entity.alumno = null;
		}
	}
}
#pragma warning restore 1591
